<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" ignored="2" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="15" started-at="2019-06-04T07:56:52Z" finished-at="2019-06-04T07:56:52Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="15" started-at="2019-06-04T07:56:52Z" finished-at="2019-06-04T07:56:52Z">
      <class name="com.magic.web.tests.LoginTest">
        <test-method status="FAIL" signature="beforeSuite()[pri:0, instance:com.magic.web.tests.LoginTest@2cb4c3ab]" name="beforeSuite" is-config="true" duration-ms="23" started-at="2019-06-04T07:56:52Z" finished-at="2019-06-04T07:56:52Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[FailedTestsScreenshots does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: FailedTestsScreenshots does not exist
at org.apache.commons.io.FileUtils.verifiedListFiles(FileUtils.java:1741)
at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1716)
at com.magic.utils.GenericUtil.cleanUpFolder(GenericUtil.java:63)
at com.magic.web.TestBase.beforeSuite(TestBase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="SKIP" signature="loginTest()[pri:0, instance:com.magic.web.tests.LoginTest@2cb4c3ab]" name="loginTest" duration-ms="0" started-at="2019-06-04T07:56:52Z" finished-at="2019-06-04T07:56:52Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[FailedTestsScreenshots does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: FailedTestsScreenshots does not exist
at org.apache.commons.io.FileUtils.verifiedListFiles(FileUtils.java:1741)
at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1716)
at com.magic.utils.GenericUtil.cleanUpFolder(GenericUtil.java:63)
at com.magic.web.TestBase.beforeSuite(TestBase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="SKIP" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.magic.web.tests.LoginTest@2cb4c3ab]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-06-04T07:56:52Z" finished-at="2019-06-04T07:56:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="generateReport()[pri:0, instance:com.magic.web.tests.LoginTest@2cb4c3ab]" name="generateReport" is-config="true" duration-ms="0" started-at="2019-06-04T07:56:52Z" finished-at="2019-06-04T07:56:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReport -->
      </class> <!-- com.magic.web.tests.LoginTest -->
      <class name="com.magic.web.tests.HotelBookingTest">
        <test-method status="SKIP" signature="searchHotelTest()[pri:1, instance:com.magic.web.tests.HotelBookingTest@13c78c0b]" name="searchHotelTest" duration-ms="0" started-at="2019-06-04T07:56:52Z" finished-at="2019-06-04T07:56:52Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[FailedTestsScreenshots does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: FailedTestsScreenshots does not exist
at org.apache.commons.io.FileUtils.verifiedListFiles(FileUtils.java:1741)
at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1716)
at com.magic.utils.GenericUtil.cleanUpFolder(GenericUtil.java:63)
at com.magic.web.TestBase.beforeSuite(TestBase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchHotelTest -->
        <test-method status="SKIP" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.magic.web.tests.HotelBookingTest@13c78c0b]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-06-04T07:56:52Z" finished-at="2019-06-04T07:56:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.magic.web.tests.HotelBookingTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
